### ISSUE TITLE
Is "Hotfix 3" included in the VFP9SP2RT.exe ?

### ISSUE THREAD

**Issue by mattslay** [VFPX/VFPRuntimeInstallers#2]
Can you please indicate if the VFP9SP2RT.exe download includes the "Hotfix 3" which is available from the VFPx site?

If not, it should be made clear in the Readme page that there are additional installation steps required to bring a VFP Runtime installation up the very latest updated state, and, you should probably add that "Hotfix 3" file to this repo.

Here's a link to "Hotfix 3" on VFPx.

https://vfpx.codeplex.com/wikipage?title=VFP%209%20SP2%20Hotfix%203%20Download%20(latest%20one)

**Comment by Woody-Soft** [comment]
Hi Matt,
Sorry that I saw your question only now.  
Of course that Hotfix 3 is included. (as it is stated in the Readme: "These installers include the all the latest hotfixes"  
If stil in doubt, just take a look at the Version number, which is 9.0.7423 both in the Hotfix3 and this Runtime-Package.
